"""
Stage 1 Training — Fine-tune YOLOv8m on SoccerNet Player Detection.

Usage
-----
# Full training:
python training/train_yolo.py

# Quick test (2 epochs, small batch):
python training/train_yolo.py --quick-test

# Custom config:
python training/train_yolo.py --config config.yaml --device cuda
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Allow imports from project root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import yaml
from ultralytics import YOLO

from src.utils import load_config, get_device


# ---------------------------------------------------------------------------
# Dataset YAML builder
# ---------------------------------------------------------------------------

_DATASET_YAML_TEMPLATE = """\
# Auto-generated by train_yolo.py
# Place SoccerNet detection images/labels under data/soccernet_detection/
path: {root}
train: images/train
val:   images/val
test:  images/test

nc: 1
names:
  0: player
"""


def ensure_dataset_yaml(data_dir: str, config: dict) -> str:
    """
    Write a minimal dataset.yaml if one does not already exist.
    Returns the path to the yaml file.
    """
    data_path = Path(data_dir)
    yaml_path = data_path / "dataset.yaml"

    if yaml_path.exists():
        return str(yaml_path)

    data_path.mkdir(parents=True, exist_ok=True)
    yaml_path.write_text(_DATASET_YAML_TEMPLATE.format(root=str(data_path.resolve())))
    print(f"[train_yolo] Created dataset stub at {yaml_path}")
    print(
        "[train_yolo] Download SoccerNet detection data and place under "
        f"{data_path}/images/{{train,val,test}} and labels/{{train,val,test}}"
    )
    return str(yaml_path)


# ---------------------------------------------------------------------------
# Training entry point
# ---------------------------------------------------------------------------

def train(args: argparse.Namespace) -> None:
    cfg = load_config(args.config)
    yolo_cfg = cfg["training"]["yolo"]

    device = args.device or get_device(cfg["detector"].get("device"))

    # Apply quick-test overrides
    if args.quick_test:
        print("[train_yolo] QUICK-TEST mode: small epochs & batch.")
        epochs     = yolo_cfg["quick_test_epochs"]
        batch_size = yolo_cfg["quick_test_batch_size"]
        imgsz      = yolo_cfg["quick_test_imgsz"]
    else:
        epochs     = args.epochs or yolo_cfg["epochs"]
        batch_size = yolo_cfg["batch_size"]
        imgsz      = yolo_cfg["imgsz"]

    data_yaml = ensure_dataset_yaml(
        "data/soccernet_detection", cfg
    )

    model = YOLO(yolo_cfg["model"])   # downloads yolov8m.pt if not cached
    print(f"[train_yolo] Starting training on device={device}")

    results = model.train(
        data=data_yaml,
        epochs=epochs,
        imgsz=imgsz,
        batch=batch_size,
        lr0=yolo_cfg["lr0"],
        lrf=yolo_cfg["lrf"],
        momentum=yolo_cfg["momentum"],
        weight_decay=yolo_cfg["weight_decay"],
        warmup_epochs=yolo_cfg["warmup_epochs"] if not args.quick_test else 0,
        device=device,
        workers=yolo_cfg["workers"] if not args.quick_test else 0,
        project=yolo_cfg["project"],
        name=yolo_cfg["name"] + ("_quicktest" if args.quick_test else ""),
        exist_ok=True,
        verbose=True,
    )

    # Copy best weights to models/
    best_weights = Path(yolo_cfg["project"]) / (
        yolo_cfg["name"] + ("_quicktest" if args.quick_test else "")
    ) / "weights" / "best.pt"

    dest = Path("models/yolov8m_players.pt")
    dest.parent.mkdir(exist_ok=True)

    if best_weights.exists():
        import shutil
        shutil.copy(best_weights, dest)
        print(f"[train_yolo] Best weights copied to {dest}")
    else:
        print(f"[train_yolo] Best weights not found at {best_weights}.")

    print("[train_yolo] Training complete.")
    return results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Fine-tune YOLOv8m for player detection."
    )
    p.add_argument("--config", default="config.yaml", help="Path to config.yaml")
    p.add_argument("--device", default=None, help="cuda / cpu / mps")
    p.add_argument("--epochs", type=int, default=None, help="Override epoch count")
    p.add_argument(
        "--quick-test",
        action="store_true",
        help="2-epoch quick test to verify the pipeline runs end-to-end",
    )
    return p


if __name__ == "__main__":
    train(build_parser().parse_args())
